group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: VsS0LGWjIkTJUVIf3YZrnpKq2ZcQ6vBV6JVAqy7xiN1QprYtul/T73RKhSimAv8CjZyRQbS+stTl37QThX13judp7hF2cFyrERbRJbPlaq+9QxvHXibIs+Xl/ovmsis/5my1Ik4i4RQDAgZ+kr4EbFQ4LCL7B8StoLZa17eBI4SXfLQnkyqVn6ydyBc+U6Fb+T9SQtJ2y2t7belTqOGjpxDdYRRaLZNhNWP6hsZgA5JNwGLAMHdTCmKRhBnA0uL2Jq7itPM5ghlsEMGs8dDQ3snNkctb4hTbWnnWsa7CXVn4dSN39JDHZr1U58iiP5JDlLnpSHP7tZrembUNhBdd3+TriaO1egvAnnTLHVN9a/yCGysGpsSI/PBYN4qzZ0Aw3VmDyGwvGq7ONOtPZpaE4oBYS2Lj8GA9YG5WFIBPEhpY+Y232/9yCjQj7v1Yn4pmFzYNqtilyoox/kN/W5HHHBKLLKpFrxjy5DYvad2BOpTc9Ov6GV0WqIBA/Yw+OvLoMB5xW5v1mSw39Ns5HwfedwhCd+5OHm0wX4gsYhD6USJ+w/Z0P9bwVzfchHnuj83ZWQ7Z9M3CV+YHjteRNXa2qlDZjV1XxDRDTc/PWuopqf3OkIdtpmlWT++lKbgPYtxsNKSCmbPdli8SybhaVXyXG39IUaK1/LO0IbVJgjTvCpo=
  - secure: n4lGrFog4/yUqbVNO/ASmG5iRkgzVgueOORPEYO5rlABpE7nottjwG/m5HoKJZA0ag7aJmws1jt8oI5IIsb8xTLbl0/f7Uy2YIV/5dAax9MhOCG7i/02J191k2SadlxtJoxtp9Z13WALlUiUPBlQQ6D//P52xJd23MqBvWMqWuGO3otW/dhEB50Gy7lYX0WM7PefvgXKBBJXy3vSWhlXMDAzd4t8S0CK8sNCnD7InjmuhFZ8w2ctfA6hKBg1OFZTzWPzIiXIn35lnsNw6P+suRES+/S05MS9pNEgrh2T1rzvmLZz+lW4Xl89l+XwflO1g1qmyve8Y8W8rKplrUHwzJxeE1RN3yHJmHRBJAHcy12uV3zWz5Svq+cl/Yoxrqx1PkgwnWdPDnLgk6FJOMR6LKDDxvL6oO53jScHA2rsiCOfunZOlgFtgO1MFRAWtU7g9ZuBxoCmNwuem6NWrrnkPwSilvaWArKo+FV/7qghfZl22Y4dBQK5J5zkCgUsvLoNnAMyIwrKe3ikZXrXSbdVt2W7q5zMMLdoL0SsxepwMzg1ZDpAnnp2xgi4xgJpydVwPppWWsbiBsmM2kM0VzvFXmzAg157R49JFm5pFWfYQ5o89SAuQ21GnXBvBkK13dzrUj7hKsEmgpTcYL7hiibRs0INshz7lb3cThums3MA6Ts=
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
